### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by zCodeAlias** [Reloaded-Project/Reloaded.Assembler#2]
I wrote a class (90% copied from yours) that converts asm string code to byte array using Fasm.

I am able to convert the code below when I compile for x86 whereas if I do it for x64 then it throws a null reference exception at certain place in the class, though the code is same and just platform was switched (I can share the class if needed).

Could it be related to the way memory is allocated in the process (which is allocated using VirtualAllocEx)...?

string[] testAsmCode = new string[]
{
  "push ebp",
  "mov eax, [ebp+8]",
  "mov edx, [ebp+12]",
  "add eax, edx",
  "pop ebp",
  "ret"
};

AsmToByteArray(testAsmCode, out byte[] asmBytes);

Any help would be appreciated...

**Comment by Sewer56** [comment]
I do think sharing the source (and exception details) here would be advisable. At the very least so the issue could be reproduced.

Technically it's a user error here but I'm down to see if I can pinpoint the issue ;3, curiosity has the best of us.

**Comment by Sewer56** [comment]
Yesterday was a busy day so sorry for the late reply.

In either case, chances are your issue is the fact you're not allocating memory in the first 2GB of the process' address space.

As you may or may not know, FASM itself was written in x86 assembly. The x86_64 version isn't a true port of FASM to the new platform (as that would take considerable effort in assembler). Instead, it's more of a wrapper/compatibility shim that still uses the x86 code, just on a new platform; replacing registers via macros etc. where necessary.

As such it's unable to work with memory higher than the first 2GB of virtual memory address space.

**Comment by zCodeAlias** [comment]
Ohhh! I see...just checked and it seems like this is the issue...i will fix it asap. Thanks a lot for the help!

**Comment by zCodeAlias** [comment]
Hello again! The problem is solved now...

I found that at the addresses that were <0x7FFFFFFF in x64 config, VirtualAlloc was allocation memory at an address >0x7FFFFFFF even though the address of the 32 bit range was being passed as "IpAddress"...

Maybe if searches ahead to find it's own addr or maybe it doesn't consider the address being passed, which is not the case because in 32 bit is was considering (not sure)...anyways...

I managed to get the x64 bit config app allocate memory in itself within 32 bit address range by setting the post build event in properties to :

call "$(DevEnvDir)..\tools\vsdevcmd.bat"
editbin /largeaddressaware:no "$(TargetPath)" 

...i consider my issue solved here...but if you have something to share or some way to do it without setting this post build event (like you did in your project) then it would be really appreciated...but otherwise also it's fine now.

I will close/ continue with the issue depending on your response :D

Thanks again for your time!
